sudo: false
language: scala
jdk: oraclejdk8
script:
- sbt dist/mkPack
- cd test/benchmarks && sbt "jmh:run  scala.collection.mutable.ArrayOpsBenchmark"
addons:
  apt:
    packages:
    - oracle-java8-installer
