# GCE VMs have better performance (will be upgrading to premium VMs soon)
sudo: required

language: scala
jdk: openjdk11

stages:
  - name: build

jobs:
    include:
      - stage: build
        script:
          - sbt -warn setupPublishCore generateBuildCharacterPropertiesFile publishLocal
          - STARR=`cat buildcharacter.properties | grep ^maven.version.number | cut -d= -f2` && echo $STARR
          - sbt -Dstarr.version=$STARR -warn setupValidateTest test:compile info testAll
